config/routes.rb
Rails.application.routes.draw do

  get 'test'=>'test#index'

  namespace :admin do
    resources :forums
  end

  get 'install'=>'install#setting'
  match 'users/login'=>'users#login',:as=>'login',:via=>[:get,:post]
  match 'user/forgot'=>'users#forgot',:as=>'forgot',:via=>[:get,:post]
  match 'users/register'=>'users#register',:as=>'register',:via=>[:get,:post]
  match 'users/following'=>'users#following',:as=>'following',:via=>[:get]
  match 'users/logout'=>'users#logout',:as=>'logout',:via=>[:get]
  match 'users/show'=>'users#register',:as=>'u',:via=>[:get]

  resources :followings

  resources :forums do
  end

  resource :topics
  resource :comments

  root 'main#index'

end

app/models/following.rb
class Following < ActiveRecord::Base
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :set_following, only: [:show, :edit, :update, :destroy]

  # GET /followings
  # GET /followings.json
  def index
    @followings = Following.all
  end

  # GET /followings/1
  # GET /followings/1.json
  def show
  end

  # GET /followings/new
  def new
    @following = Following.new
  end

  # GET /followings/1/edit
  def edit
  end

  # POST /followings
  # POST /followings.json
  def create
    @following = Following.new(following_params)

    respond_to do |format|
      if @following.save
        format.html { redirect_to @following, notice: 'Following was successfully created.' }
        format.json { render :show, status: :created, location: @following }
      else
        format.html { render :new }
        format.json { render json: @following.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /followings/1
  # PATCH/PUT /followings/1.json
  def update
    respond_to do |format|
      if @following.update(following_params)
        format.html { redirect_to @following, notice: 'Following was successfully updated.' }
        format.json { render :show, status: :ok, location: @following }
      else
        format.html { render :edit }
        format.json { render json: @following.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followings/1
  # DELETE /followings/1.json
  def destroy
    @following.destroy
    respond_to do |format|
      format.html { redirect_to followings_url, notice: 'Following was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_following
      @following = Following.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def following_params
      params.require(:following).permit(:user_id, :object_id)
    end
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/views/followings/_form.html.erb
<%= form_for(@following) do |f| %>
  <% if @following.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@following.errors.count, "error") %> prohibited this following from being saved:</h2>

      <ul>
      <% @following.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :object_id %><br>
    <%= f.number_field :object_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/followings/edit.html.erb
<h1>Editing following</h1>

<%= render 'form' %>

<%= link_to 'Show', @following %> |
<%= link_to 'Back', followings_path %>

app/views/followings/index.html.erb
<h1>Listing followings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Object</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @followings.each do |following| %>
      <tr>
        <td><%= following.user_id %></td>
        <td><%= following.object_id %></td>
        <td><%= link_to 'Show', following %></td>
        <td><%= link_to 'Edit', edit_following_path(following) %></td>
        <td><%= link_to 'Destroy', following, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Following', new_following_path %>

app/views/followings/new.html.erb
<h1>New following</h1>

<%= render 'form' %>

<%= link_to 'Back', followings_path %>

app/views/followings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @following.user_id %>
</p>

<p>
  <strong>Object:</strong>
  <%= @following.object_id %>
</p>

<%= link_to 'Edit', edit_following_path(@following) %> |
<%= link_to 'Back', followings_path %>