config/routes.rb
Rails.application.routes.draw do

  get 'test'=>'test#index'

  namespace :admin do
    resources :forums
  end

  get 'install'=>'install#setting'
  match 'users/login'=>'users#login',:as=>'login',:via=>[:get,:post]
  match 'user/forgot'=>'users#forgot',:as=>'forgot',:via=>[:get,:post]
  match 'users/register'=>'users#register',:as=>'register',:via=>[:get,:post]
  match 'users/following'=>'users#following',:as=>'following',:via=>[:get]
  match 'users/logout'=>'users#logout',:as=>'logout',:via=>[:get]
  match 'users/show'=>'users#register',:as=>'u',:via=>[:get]

  resources :followings

  resources :forums do
  end

  resource :topics
  resource :comments

  root 'main#index'

end

app/models/user.rb
#coding: utf-8

class User < ActiveRecord::Base

  #attr_accessible :avatar_path, :email, :login_date, :memo, :password, :pass, :point, :reg_date, :username, :code, :password_confirmation,:signatures

  has_many :comments, :dependent => :destroy
  has_many :places
  has_many :topics
  has_many :guides
  has_many :articles
  has_many :albums
  has_many :photos
  has_many :eventses
  has_many :been_to_places
  has_one :avatar

  #权限控制
  has_and_belongs_to_many :permissions

  validates_presence_of :email, :message => "邮箱不能为空!"
  validates_format_of :email, :message => "邮箱格式不正确!", :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_length_of :email, :minimum => 3, :maximum => 15, :message => "邮箱长度须为3到15位字母或数字!"
  validates_uniqueness_of :email, :case_sensitive => false, :message => "该邮箱地址已存在!"

  validates_presence_of :username, :message => "用户名不能为空!"
  validates_length_of :username, :minimum => 2, :maximum => 15, :message => "用户长度须为2到15位字母或数字!"
  validates_uniqueness_of :username, :message => "该用户名已存在!"

  validates_presence_of :password, :message => "密码不能为空!"
  validates_length_of :password, :minimum => 5, :message => "密码长度须为5到16位字母或数字! "
  validates_confirmation_of :password, :message => "两次密码不一致!"

  #注册时邮件激活码
  validates_presence_of :code, :message => "邮箱激活码不能为空!", :on => :create

  #自定义验证方法
  validate :check_code, :on => :create

  #对明文密码加密
  before_create :generate_password

  #before_destroy :before_delete_user

  #选用已有的所有的验证程序来验证模型，
  #validates :email, :length => {:in => 1..25}, :uniqueness => true

  #自定义验证方法
  #validate :must_be_friends

  #或随着块一起验证当前记录
  #validate do |cur|
  #  cur.must_be_friends
  #end

  #或
  #validate do
  #  errors.add(:base, "Must be friends to leave a comment") unless commenter.friend_of?(commentee)
  #end

  def code
    @code
  end

  def code=(str)
    @code=str
  end

  #对外提供邮箱激活码
  def self.get_activecode(email)
    generate_activecode(email)
  end

  #登录
  def self.login(post={})
    user=nil
    back={:error => nil, :uid => nil, :user => nil}
    if post[:email] && post[:password]
      user=User.find_by_email post[:email]
    elsif post[:account] && post[:password]
      if /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i.match post[:account]
        user=User.find_by_email post[:account]
      else
        user=User.find_by_username post[:account]
      end
    elsif post[:username] && post[:password]
      user=User.find_by_username post[:username]
    else
      back[:error] = '很抱歉，登录邮箱/用户名或密码不能为空'
    end

    if user
      if user[:password]==Digest::MD5.hexdigest(post[:password])
        user.login_date=Time.now
        user.save
        back[:uid]=user[:id]
        back[:user]=user
        back[:success]='登录成功！'
      else
        back[:error]='很抱歉，密码错误，请重新输入'
      end
    else
      back[:error]='很抱歉，帐号不存在，请重试或注册'
    end

    return back

  end

  private

  #保存session

  #检查激活码
  def check_code
    errors.add(:base, "邮件激活码不正确") if @code&&@code!=generate_activecode(email)
  end

  def must_be_friends
    errors.add(:base, "Must be friends to leave a comment") unless commenter.friend_of?(commentee)
  end

  def before_delete_user
    if comments.empty?
      return true
    else
      errors.add(:base, 'error smsmsmsm')
      return false
    end
  end

  #生成注册激活码
  def generate_activecode(email)
    Digest::SHA1.hexdigest('gobiker2013'+email)
  end

  #生成正式密码
  def generate_password
    #salt=Array.new(5) { rand(1024).to_s(36) }.join
    #self.password=Digest::SHA256.hexdigest(self.password+salt)
    self.password=Digest::MD5.hexdigest(self.password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
  end

  def register
  end

  def show
  end

  def logout
  end

  def following
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user,options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  #生成注册激活码
  def generate_activecode(str)
    Digest::SHA1.hexdigest('gobiker2013'+str)
  end
end

app/views/users/following.html.erb
<h1>Users#following</h1>
<p>Find me in app/views/users/following.html.erb</p>

app/views/users/login.html.erb
<div class="container wrap">

  <div class="row min-inner session-edge">
    <div class="col-xs-12 col-md-offset-1 col-md-10">
      <h2 class="big-title">登录</h2>
      <h3 class="slug">最专业的中文开发者技术问答社区</h3>
      <p class="title-description">如果你有下列任何一个帐号，点击对应按钮登录，无需注册</p>

      <div class="auth-login">
        <p>
          <a class="auth-big" href="https://segmentfault.com/user/oauth/google"><i class="i-google-big"></i>Google</a>
          <a class="auth-big" href="https://segmentfault.com/user/oauth/github"><i class="i-github-big"></i>GitHub</a>
          <a class="auth-big" href="https://segmentfault.com/user/oauth/weibo"><i class="i-weibo-big"></i>新浪微博</a>
          <a class="auth-big" href="https://segmentfault.com/user/oauth/qq"><i class="i-qq-big"></i>腾讯QQ</a>
          <a class="more-arrow" href="###"></a>
        </p>
        <p id="more-arrow" class="hidden">
          <a class="auth-small" href="https://segmentfault.com/user/oauth/twitter"><i class="i-twitter"></i>Twitter</a>
          <a class="auth-small" href="https://segmentfault.com/user/oauth/facebook"><i class="i-facebook"></i>Facebook</a>
          <a class="auth-small" href="https://segmentfault.com/user/oauth/renren"><i class="i-renren"></i>人人网</a>
          <a class="auth-small" href="https://segmentfault.com/user/oauth/douban"><i class="i-douban"></i>豆瓣</a>
          <a class="auth-small" href="https://segmentfault.com/user/oauth/tqq"><i class="i-tqq"></i>腾讯微博</a>
        </p>
      </div>

      <div class="sfid-login">
        或者使用本站帐号登录 ( <a href="<%= register_path %>">注册</a> 或 <a href="<%= forgot_path %>">找回密码</a> )
        <form action="<%=login_path%>" method="post">
          <p>
            <label for="mail" class="hid">Email 地址</label>
            <input class="form-control input-lg text-34" type="email" name="mail" placeholder="Email 地址" value="" required="">
          </p>
          <p>
            <label for="password" class="hid">登录密码</label>
            <input class="form-control input-lg text-34" type="password" name="password" placeholder="登录密码" required="">
          </p>
          <button class="btn btn-primary btn-lg btn-xl" type="submit">登录</button>
          <div class="remember"><input type="checkbox" id="remember" name="remember" value="1" checked=""> <label for="remember">下次自动登录</label></div>
        </form>
      </div>
    </div>
  </div>

</div>

app/views/users/logout.html.erb
<h1>Users#logout</h1>
<p>Find me in app/views/users/logout.html.erb</p>

app/views/users/register.html.erb
<div class="container wrap">

  <div class="row min-inner session-edge">
    <div class="col-xs-12 col-md-offset-1 col-md-10">
      <h2 class="big-title">注册</h2>

      <p class="title-description">您正在注册本站独立帐号，我们推荐您使用第三方帐号登录</p>

      <form class="session-form ajaxform" action="<%= register_path %>" method="post">
        <div class="session-aside">
          如果您有下列网站帐号，可使用这些帐号<a href="<%= login_path %>">直接登录</a>，无需注册
          <a style="display: block; margin-top: 6px; text-decoration: none;" href="<%= login_path %>">
            <i class="i-google">Google</i>
            <i class="i-github">Github</i>
            <i class="i-weibo">新浪微博</i>
            <i class="i-tqq">腾讯微博</i>
            <i class="i-twitter">Twitter</i>
            <i class="i-facebook">Facebook</i>
            <i class="i-renren">人人</i>
            <i class="i-douban">豆瓣</i>
          </a>
        </div>

        <p>
          <label for="name" class="hid">常用昵称或真名</label>
          <input type="text" name="name" maxlength="32" placeholder="常用昵称或真名" value="" class="form-control input-lg text-34" required/>
        </p>

        <p>
          <label for="mail" class="hid">Email 地址</label>
          <input type="email" name="mail" placeholder="Email 地址" value="" class="form-control input-lg text-34" required/>
        </p>

        <p>
          <label for="password" class="hid">登录密码</label>
          <input type="password" name="password" placeholder="登录密码" class="form-control input-lg text-34" required/>
        </p>

        <div class="form-action">
          <span class="left">您将同意并接受<a href="#" target="_blank">《服务条款》</a></span>
          <input type="submit" class="btn btn-primary btn-lg btn-xl" value="注册"/>
        </div>
      </form>
    </div>
  </div>

</div><!-- end .wrap -->

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>