config/routes.rb
Rails.application.routes.draw do

  get 'test'=>'test#index'

  namespace :admin do
    resources :forums
  end

  get 'install'=>'install#setting'
  match 'users/login'=>'users#login',:as=>'login',:via=>[:get,:post]
  match 'user/forgot'=>'users#forgot',:as=>'forgot',:via=>[:get,:post]
  match 'users/register'=>'users#register',:as=>'register',:via=>[:get,:post]
  match 'users/following'=>'users#following',:as=>'following',:via=>[:get]
  match 'users/logout'=>'users#logout',:as=>'logout',:via=>[:get]
  match 'users/show'=>'users#register',:as=>'u',:via=>[:get]

  resources :followings

  resources :forums do
  end

  resource :topics
  resource :comments

  root 'main#index'

end

app/views/global/_user_nav_login.html.erb
<ul class="user-nav">
  <li class="has-dropdown">
    <a href="http://segmentfault.com/ask">撰写</a>
    <ul class="dropdown-item">
      <li><a href="http://segmentfault.com/ask">提出问题</a></li>
      <li><a href="http://segmentfault.com/write">撰写博客</a></li>
      <li class="hr"><a href="http://segmentfault.com/drafts">草稿</a></li>
    </ul>
  </li>
  <li class="has-dropdown">
    <a id="msg-link" href="http://segmentfault.com/user/events">消息</a>
  </li>
  <li class="has-dropdown">
    <a href="http://segmentfault.com/u/seeyoup">seeyoup <i class="i-arrow-s"></i></a>
    <ul class="dropdown-item">
      <li><a href="http://segmentfault.com/u/seeyoup">我的主页</a></li>

      <li><a href="http://blog.segmentfault.com/up">我的博客</a></li>

      <li><a href="http://segmentfault.com/user/settings">帐号设置</a></li>
      <li><a href="http://segmentfault.com/user/logout">退出</a></li>
      <li class="hr"><a href="http://segmentfault.com/faq">帮助中心</a></li>
      <li><a href="http://0x.segmentfault.com">建议反馈</a></li>
    </ul>
  </li>
</ul>

app/views/global/_user_nav_nologin.html.erb
<ul class="user-nav">
  <li>
    <a id="login-link" href="http://segmentfault.com/user/login">登录</a>
  </li>
  <li>
    <a href="http://segmentfault.com/user/register">注册</a>
  </li>
</ul>

app/views/global/footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="row inner hidden-xs">
      <dl class="col-sm-2 site-link">
        <dt>网站相关</dt>
        <dd><a href="http://segmentfault.com/about">关于我们</a></dd>
        <dd><a href="http://segmentfault.com/tos">服务条款</a></dd>
        <dd><a href="http://segmentfault.com/faq">帮助中心</a></dd>
        <dd><a href="http://segmentfault.com/q/1010000000187808">编辑器语法</a></dd>
        <dd><a href="http://weekly.segmentfault.com/">每周精选</a></dd>
      </dl>
      <dl class="col-sm-2 site-link">
        <dt>联系合作</dt>
        <dd><a href="http://segmentfault.com/hiring">加入我们</a></dd>
        <dd><a href="http://segmentfault.com/link">合作伙伴</a></dd>
        <dd><a href="http://segmentfault.com/press">媒体报道</a></dd>
        <dd><a href="http://0x.segmentfault.com">建议反馈</a></dd>
      </dl>
      <dl class="col-sm-2 site-link">
        <dt>常用链接</dt>
        <dd><a href="http://blog.segmentfault.com/devblog" target="_blank">开发日志</a></dd>
        <dd><a href="http://segmentfault.com/mobileapp">移动应用</a></dd>
        <dd><a href="http://segmentfault.com/events?category=4">黑客马拉松</a></dd>
        <dd><a href="http://yumiwan.com" target="_blank">玉米湾域名</a></dd>
        <dd><a href="http://mirrors.segmentfault.com/">文档镜像</a></dd>
      </dl>
      <dl class="col-sm-2 site-link">
        <dt>关注我们</dt>
        <dd><a href="http://segmentfault.com/feeds">问答 RSS 订阅</a></dd>
        <dd><a href="http://weibo.com/segmentfault" target="_blank">新浪微博</a></dd>
        <dd><a href="http://twitter.com/segment_fault" target="_blank">Twitter</a></dd>
        <dd><a href="http://t.qq.com/segmentfault" target="_blank">腾讯微博</a></dd>
        <dd><a href="http://page.renren.com/699146294" target="_blank">人人网</a></dd>
      </dl>
      <dl class="col-sm-4 site-link" id="license">
        <dt>内容许可</dt>
        <dd>除特别说明外，用户内容均采用 <a rel="license" target="_blank" href="http://creativecommons.org/licenses/by-sa/3.0/cn/">知识共享署名-相同方式共享 3.0 中国大陆许可协议</a> 进行许可</dd>
        <dd>本站由 <a target="_blank" href="http://elinkhost.com/">Elinkhost</a> 提供 IDC 服务<br><a target="_blank" href="https://www.upyun.com/?utm_source=segmentfault&amp;utm_medium=link&amp;utm_campaign=upyun&amp;md=segmentfault">又拍云</a> 提供 CDN 存储服务</dd>
      </dl>
    </div>
    <div class="copyright">
      Copyright &copy; 2011-2014 SegmentFault. 当前呈现版本 14.3.20 <br>京ICP备12004937号, 京公网安备110108008332号
    </div>
  </div>
</footer>


<a id="backtop" class="mobi-hide hidden" href="#body">回顶部</a>

app/views/global/header.html.erb
<input type="hidden" id="session" data-user="{&quot;id&quot;:&quot;1030000000094092&quot;,&quot;name&quot;:&quot;seeyoup&quot;,&quot;url&quot;:&quot;http:\/\/segmentfault.com\/u\/seeyoup&quot;,&quot;rank&quot;:&quot;24&quot;}"/>

<!--[if lt IE 9]>
<div class="error chromeframe">您的浏览器版本<strong>很旧很旧</strong>，为了正常地访问网站，请升级您的浏览器 <a target="_blank" href="http://browsehappy.com">立即升级</a></div>
<![endif]-->

<div class="global-nav">
  <nav class="global-nav container">
    <a href="###" id="site-nav-btn" class="visible-xs">更多</a>
    <ul class="site-nav hidden-xs">
      <li class="hidden-xs current"><a href="<%=root_path %>">首页</a></li>
      <li class=""><a href="<%= forums_path %>">话题</a></li>
      <li class=""><a href="http://segmentfault.com/tags">标签</a></li>
      <li class=""><a href="http://segmentfault.com/users">用户</a></li>
      <li class=""><a href="http://segmentfault.com/badges">徽章</a></li>
      <li class=""><a href="http://segmentfault.com/events">活动</a></li>
    </ul>


    <%= render 'global/user_nav_login' %>



  </nav>
  <!-- end .global-nav -->
</div>
<header class="site-header">
  <div class="container inner clearfix">
    <div class="head-name">
      <a href="http://segmentfault.com/">
        <span class="head-logo">SegmentFault</span>
        <strong>问答</strong>
      </a>
    </div>
    <div class="head-search">
      <form id="search" action="http://segmentfault.com/search">
        <input type="text" class="form-control text-27 input-search" name="q" autocomplete="off" spellcheck="false" placeholder="搜索问题，标签，用户">
        <button class="btn-search" type="submit">搜索</button>
      </form>
    </div>
    <ul class="head-nav">
      <li class="current"><a href="http://segmentfault.com/">技术问答</a></li>
      <li><a href="http://segmentfault.com/101">新手问答</a></li>
      <li><a href="http://segmentfault.com/openhw">开源硬件</a></li>
      <li><a href="http://segmentfault.com/sites">子站问答</a></li>
    </ul>
    <div class="head-misc">
      <span>找不到答案？</span> <a class="btn btn-primary action" href="<%=new_topics_path%>">+ 新帖</a>
    </div>
  </div>
</header>
<!-- end .site-header -->